name: Bug Report
description: File a bug report
title: "[BUG] "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see...
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: input
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: I expected...
    validations:
      required: true
  - type: input
    id: ide
    attributes:
      label: IDE
      description: Which IDE were you using?
      placeholder: e.g., PyCharm, Clion, VSCode
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system were you using?
      placeholder: e.g., iOS, Windows 10, Ubuntu 20.04, WSL
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: More details...
    validations:
      required: false
