blank_issues_enabled: true
contact_links:
  - name: ARU GitHub Org Discussions
    url: https://github.com/orgs/African-Robotics-Unit/discussions
    about: General code discussions within the ARU GitHub Org.
  - name: ARU Website
    url: https://africanroboticsunit.com
    about: The ARU website.
