# This issue form is shared to all public repositories in the ARU GitHub Org
# and is intended to address anyone seeking to interact with the ARU GitHub Org,
# particularly new students.

name: ARU Organisation Join Request
description: Request to Join or to Collaborate with the ARU GitHub Org
title: ARU Org Join Request
labels:
  - "join request"
assignees:
  - "LawrenceStanton"

body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in joining the ARU GitHub Org. This form is used to request access to the ARU GitHub Org.

        > If submitting this issue in any repository other than [`African-Robotics-Unit/.github`](https://github.com/African-Robotics-Unit/.github), this will be assumed to be a request to collaborate on that repository only.

        The [African Robotics Unit (ARU) GitHub Organisation](https://github.com/African-Robotics-Unit) is a private organisation for ARU postgraduate students and staff.
        If you are eligible to join, you may be admitted as a member to this organisation.

        4th Year students, students outside of the Department of Electrical Engineering, and collaborators external to UCT are ineligible to join as members, but may rather be added as collaborators to specific repositories.

  - type: input
    id: name
    attributes:
      label: Your Name
      description: Your real name.
      placeholder: John Doe
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Membership Type
      description: Please confirm whether you are requesting to join the ARU GitHub Org as a member or as a collaborator.
      options:
        - Member
        - Collaborator
    validations:
      required: true

  - type: dropdown
    id: role
    attributes:
      label: Role
      description: Your role.
      options:
        - Undergraduate
        - Postgraduate
        - Staff
        - External Collaborator
    validations:
      required: true

  - type: dropdown
    id: supervisor
    attributes:
      label: Supervisor
      description: Your supervisor.
      options:
        - "Amir Patel"
        - "Paul Amayo"
        - "Stacey Shield"
        - "Robyn Verrinder"
        - "Boitumelo Dikoko"
        - "Leanne Raw"
        - "Other"
      multiple: true
    validations:
      required: false

  - type: textarea
    id: teams
    attributes:
      label: Teams
      description: |
        _For membership requests only._

        Please list the teams you require access to.
      placeholder: "* `@SHARC`"

  - type: textarea
    id: repositories
    attributes:
      label: Collaborator Repositories
      description: |
        _For collaborator requests only._

        Please list the repositories you require collaborator access to.
      placeholder: "* [`African-Robotics-Unit/.github`](https://github.com/African-Robotics-Unit/.github)"

  - type: textarea
    id: info
    attributes:
      label: Special Requests
      description: Should you require any special permissions, access to private repositories, etc. or otherwise that you require from admin, please specify them here.
      placeholder: Maintainer privileges for _this_ repository, add me as an org owner...

  - type: checkboxes
    id: conduct
    attributes:
      label: Code of Conduct
      description: |
        _Applicable to membership requests only._

        Upon joining the ARU GitHub Org, you agree to read and abide by the ARU GitHub Org Code of Conduct and its required standards.
        This may be found on the [ARU GitHub Org Overview](https://github.com/African-Robotics-Unit) page once you are admitted.
      options:
        - label: I agree.
          required: true
  - type: checkboxes
    id: email
    attributes:
      label: Email Address Confirmation
      description: |
        _Applicable to UCT Students and Staff only._

        Please note that UCT's email address filters will block all emails from GitHub. This is a hard block that will not even reach the Junk folder.
        Please therefore ensure that you either change your primary email address on GitHub to some other private email address, e.g. GMail, or explicitly authorise GitHub on your email server preferences.

        Without doing the above, you will not receive any emails from GitHub, including the invite to join the ARU GitHub Org.
      options:
        - label: I confirm that I have read and understood the above.
          required: true
