name: Join Request
description: Request to Join the ARU GitHub Org
title: ARU Org Join Request
assignees:
  - "LawrenceStanton"

body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in joining the ARU GitHub Org. Please fill out the following form to request access to the ARU GitHub Org.

  - type: input
    id: name
    attributes:
      label: Your Name
      description: Your real name.
      placeholder: John Doe
    validations:
      required: true

  - type: dropdown
    id: role
    attributes:
      label: Role
      description: Your student class or role.
      options:
        - 4th Year
        - Postgrad
        - Staff
        - External
    validations:
      required: true

  - type: dropdown
    id: supervisor
    attributes:
      label: Supervisor
      description: Your supervisor.
      options:
        - "Amir Patel"
        - "Paul Amayo"
        - "Stacey Shield"
        - "Robyn Verrinder"
        - "Boitumelo Dikoko"
        - "Leanne Raw"
        - "Other"
      multiple: true
    validations:
      required: false

  - type: checkboxes
    id: conduct
    attributes:
      label: Code of Conduct
      description: Upon joining the ARU GitHub Org, you agree to read and abide by the ARU GitHub Org Code of Conduct and its required standards. This may be found on the [ARU GitHub Org Overview](https://github.com/African-Robotics-Unit) page once you are admitted.
      options:
        - label: I agree
          required: true
