# This issue form is shared to all public repositories in the ARU GitHub Org
# and is intended to address anyone seeking to interact with the ARU GitHub Org,
# particularly new students.

name: ARU Organisation Join Request
description: Request to Join or to Collaborate with the ARU GitHub Org
title: ARU Org Join Request
labels:
  - "join request"
assignees:
  - "LawrenceStanton"

body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in joining the ARU GitHub Org. This form is used to request access to the ARU GitHub Org.

        The [African Robotics Unit (ARU) GitHub Organisation](https://github.com/African-Robotics-Unit) is a private organisation for ARU postgraduate students and staff.
        If you are eligible to join, you may be admitted as a member to this organisation.

        4th Year students, students outside of the Department of Electrical Engineering, and collaborators external to UCT are ineligible to join as members, but may rather be added as collaborators to specific repositories.

  - type: input
    id: name
    attributes:
      label: Your Name
      description: Your real name.
      placeholder: John Doe
    validations:
      required: true

  - type: dropdown
    id: role
    attributes:
      label: Role
      description: Your role.
      options:
        - Undergraduate
        - Postgraduate
        - Staff
        - External Collaborator
    validations:
      required: true

  - type: dropdown
    id: supervisor
    attributes:
      label: Supervisor
      description: Your supervisor.
      options:
        - "Amir Patel"
        - "Paul Amayo"
        - "Stacey Shield"
        - "Robyn Verrinder"
        - "Boitumelo Dikoko"
        - "Leanne Raw"
        - "Other"
      multiple: true
    validations:
      required: false

  - type: textarea
    id: teams
    attributes:
      label: Teams
      description: |
        _For membership requests only._

        Please list the teams you require access to.
      placeholder: "`@SHARC`"

  - type: textarea
    id: repositories
    attributes:
      label: Collaborator Repositories
      description: |
        _For collaborator requests only._

        Please list the repositories you require access to.
      placeholder: "[`African-Robotics-Unit/.github`](https://github.com/African-Robotics-Unit/.github)"

  - type: textarea
    id: info
    attributes:
      label: Special Requests
      description: Should you require any special permissions, access to private repositories, etc. or otherwise that you require from admin, please specify them here.
      placeholder: Maintainer privileges for the [`.github-private`](https://github.com/African-Robotics-Unit/.github-private) repository, add me as an org owner...

  - type: checkboxes
    id: conduct
    attributes:
      label: Code of Conduct
      description: |
        _For membership requests only._

        Upon joining the ARU GitHub Org, you agree to read and abide by the ARU GitHub Org Code of Conduct and its required standards.
        This may be found on the [ARU GitHub Org Overview](https://github.com/African-Robotics-Unit) page once you are admitted.
      options:
        - label: I agree
        - label: N/A
          required: true
